#!/usr/bin/env php
<?php
declare(strict_types=1);

// autoload
$autoloadFiles = [__DIR__ . '/../vendor/autoload.php', __DIR__ . '/../../../autoload.php'];
foreach ($autoloadFiles as $autoloadFile) {
    if (file_exists($autoloadFile)) {
        require_once $autoloadFile;
        break;
    }
}

require_once __DIR__ . '/Background.php';
require_once __DIR__ . '/Daemon.php';

// use
use Symfony\Component\Console\Application;

// lets go!
$application = new Application('my-test');
$application->addCommands([
    new Background(),
    new Daemon(),
]);

$application->run();
